title: "the Emiola lab"
description: "microbial therapeutics unit"
url: https://www.emiolalab.com
logo: /images/logo.png

author:
  name: Akintunde Emiola

markdown: kramdown
permalink: /:categories/:title/
future: true
sass:
  sass_dir: css

kramdown:
  parse_block_html: true

plugins:
  - jekyll-sitemap
  - jekyll-feed

feed:
  categories:
    - news

exclude:
  - "*.branches"
  - "*.class"
  - "*.cpp"
  - "*.csv"
  - "*.fasta"
  - "*.gz"
  - "*.h"
  - "*.hh"
  - "*.ipynb"
  - "*.jar"
  - "*.java"
  - "*.kml"
  - "*.log"
  - "*.mcc"
  - "*.nb"
  - "*.newick"
  - "*.nex"
  - "*.py"
  - "*.R"
  - "*.rb"
  - "*.Rmd"
  - "*.tiff"
  - "*.tips"
  - "*.trees"
  - "*.tsv"
  - "*.zip"
  - "Gemfile"
  - "Gemfile.lock"
  - "README.md"
